### PR TITLE
The "Save to Site" bookmarklet, revived through a plugin's external dependency

### LINKED ISSUE #130: The Press-to-Save Bookmarklet is broken in several ways.
> I simply wanted to let you know that the bookmarklet for the Link Roundups plugin is broken. It will not let me add the bookmarklet to any browser, there is no text to copy to manually add the bookmarklet, and the mobile link also does not work.

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- [x] In the admin page to install the bookmarklet, if the code that is used to generate the bookmarklet URI is not returning a bookmarklet, then site admins are encouraged to install an official WordPress plugin created for WordPress 4.9 that brought back the "Press this!" code that this plugin currently depends upon.
- [x] Uses function provided by https://wordpress.org/plugins/press-this/ to generate the bookmarklet link
- [x] Updates docs
- [x] Resolves #130.

If a site is not capable of creating the bookmarklet and the current user is capable of installing plugins:

Screen Shot 2019-05-13 at 20 04 24

> Save to Site is a tool that lets you send Saved Links to your WordPress Dashboard while browsing the web.
>
> Your website is not currently capable of generating the link used for the Save to Site bookmarklet. In order to use the Save to Site bookmarklet, you will need to install the official WordPress plugin Press This, which reimplements functionality that was removed from WordPress in version 4.9.

If the site is not capable of creating the bookmarklet and the current user cannot install plugins:

Screen Shot 2019-05-13 at 20 35 13

If the site is capable of creating the bookmarklet, then the page's appearance is unchanged: 

Screen Shot 2019-05-13 at 20 05 01

### CODE REVIEW

File: inc/link-roundups/class-save-to-site-button.php [hunk 1]
```diff
@@ -55,14 +55,29 @@ public static function init() {
...
 		// This is the default 'Press This!' button link.
-		$shortcut_link = htmlspecialchars( get_shortcut_link() );
+		$shortcut_link = '';
+
+		if ( function_exists( 'get_shortcut_link' ) ) {
+			$shortcut_link = htmlspecialchars( get_shortcut_link() );
+		}
+
+		// since 4.9, get_shortcut_link has returned the empty string.
+		if ( empty( $shortcut_link ) && function_exists( 'press_this_get_shortcut_link' ) ) {
```
Comment (joshdarby) [inline inc/link-roundups/class-save-to-site-button.php]: @benlk Do you think it'd be beneficial here to also make sure the WP version is greater than 4.9?

Comment (benlk) [reply inc/link-roundups/class-save-to-site-button.php]: I don't think it's necessary; we're less concerned about what version of WordPress is in use and more concerned about whether that version of WordPress provides the link. Checking the WordPress version is a way of getting a clue as to whether the link would be provided, but it's easier to just test whether the link is provided.

Comment (benlk) [reply inc/link-roundups/class-save-to-site-button.php]: Update: https://github.com/INN/link-roundups/issues/166
